export type areaTitle =
    | 'Square kilometer'
    | 'Hectare'
    | 'Are'
    | 'Square meter'
    | 'Square decimeter'
    | 'Square centimeter'
    | 'Square millimeter'
    | 'Square micron'
    | 'Acre'
    | 'Square mile'
    | 'Square yard'
    | 'Square foot'
    | 'Square inch'
    | 'Square rod'
    | 'Qing'
    | 'Mu'
    | 'Square chi'
    | 'Square cun'
    | 'Square gongli';

export type areaMetrics =
    | 'km²'
    | 'ha'
    | 'a'
    | 'm²'
    | 'dm²'
    | 'cm²'
    | 'mm²'
    | 'μm²'
    | 'ac'
    | 'mile²'
    | 'yd²'
    | 'ft²'
    | 'in²'
    | 'rd²'
    | 'qing'
    | 'mu'
    | 'chi²'
    | 'cun²'
    | 'gongli²';
