import { IOption } from '../../types';

interface IOptions {
    [key: string]: IOption[];
}

export const options: IOptions = {
    length: [
        { title: 'Kilometer', metrics: 'km' },
        { title: 'Meter', metrics: 'm' },
        { title: 'Decimeter', metrics: 'dm' },
        { title: 'Centimeter', metrics: 'cm' },
        { title: 'Millimeter', metrics: 'mm' },
        { title: 'Micrometer', metrics: 'μm' },
        { title: 'Nanometer', metrics: 'nm' },
        { title: 'Picometer', metrics: 'pm' },
        { title: 'Nautical mile', metrics: 'nmi' },
        { title: 'Mile', metrics: 'mi' },
        { title: 'Femara', metrics: 'fur' },
        { title: 'Fathom', metrics: 'ftm' },
        { title: 'Yard', metrics: 'yd' },
        { title: 'Foot', metrics: 'ft' },
        { title: 'Inch', metrics: 'in' },
        { title: 'Gongli', metrics: 'gongli' },
        { title: 'Li', metrics: 'li' },
        { title: 'Zhang', metrics: 'zhang' },
        { title: 'Chi', metrics: 'chi' },
        { title: 'Cun', metrics: 'cun' },
        { title: 'Fen', metrics: 'fen' },
        { title: 'Hao', metrics: 'hao' },
        { title: 'Parsec', metrics: 'pc' },
        { title: 'Lunar distance', metrics: 'ld' },
        { title: 'Astronomical unit', metrics: '☉' },
        { title: 'Light year', metrics: 'ly' },
    ],
    area: [
        { title: 'Square kilometer', metrics: 'km²' },
        { title: 'Hectare', metrics: 'ha' },
        { title: 'Are', metrics: 'a' },
        { title: 'Square meter', metrics: 'm²' },
        { title: 'Square decimeter', metrics: 'dm²' },
        { title: 'Square centimeter', metrics: 'cm²' },
        { title: 'Square millimeter', metrics: 'mm²' },
        { title: 'Square micron', metrics: 'μm²' },
        { title: 'Acre', metrics: 'ac' },
        { title: 'Square mile', metrics: 'mile²' },
        { title: 'Square yard', metrics: 'yd²' },
        { title: 'Square foot', metrics: 'ft²' },
        { title: 'Square inch', metrics: 'in²' },
        { title: 'Square rod', metrics: 'rd²' },
        { title: 'Qing', metrics: 'qing' },
        { title: 'Mu', metrics: 'mu' },
        { title: 'Square chi', metrics: 'chi²' },
        { title: 'Square cun', metrics: 'cun²' },
        { title: 'Square gongli', metrics: 'gongli²' },
    ],
    volume: [
        { title: 'Cubic meter', metrics: 'm³' },
        { title: 'Cubic decimeter', metrics: 'dm³' },
        { title: 'Cubic centimeter', metrics: 'cm³' },
        { title: 'Cubic millimeter', metrics: 'mm³' },
        { title: 'Hectoliter', metrics: 'hl' },
        { title: 'Liter', metrics: 'l' },
        { title: 'Deciliter', metrics: 'dl' },
        { title: 'Centiliter', metrics: 'cl' },
        { title: 'Milliliter', metrics: 'ml' },
        { title: 'Cubic foot', metrics: 'ft³' },
        { title: 'Cubic inch', metrics: 'in³' },
        { title: 'Cubic yard', metrics: 'yd³' },
        { title: 'Acre-foot', metrics: 'af³' },
    ],
    temp: [
        { title: 'Celsius', metrics: '°C' },
        { title: 'Fahrenheit', metrics: '°F' },
        { title: 'Kelvin', metrics: 'K' },
    ],
    speed: [
        { title: 'Meter per second', metrics: 'm/s' },
        { title: 'Kilometer per hour', metrics: 'km/h' },
        { title: 'Kilometer per second', metrics: 'km/s' },
        { title: 'Mach', metrics: 'Ma' },
        { title: 'Knot', metrics: 'kn' },
        { title: 'Mile per hour', metrics: 'mph' },
        { title: 'Foot per second', metrics: 'fps' },
        { title: 'Inch per second', metrics: 'ips' },
        { title: 'Lightspeed', metrics: 'c' },
    ],
    time: [
        { title: 'Year', metrics: 'y' },
        { title: 'Week', metrics: 'wk' },
        { title: 'Day', metrics: 'd' },
        { title: 'Hour', metrics: 'h' },
        { title: 'Minute', metrics: 'min' },
        { title: 'Second', metrics: 's' },
        { title: 'Millisecond', metrics: 'ms' },
        { title: 'Microsecond', metrics: 'μs' },
        { title: 'Picosecond', metrics: 'ps' },
    ],
    weight: [
        { title: 'Tonne', metrics: 't' },
        { title: 'Kilogram', metrics: 'kg' },
        { title: 'Gram', metrics: 'g' },
        { title: 'Milligram', metrics: 'mg' },
        { title: 'Microgram', metrics: 'μg' },
        { title: 'Pound', metrics: 'lb' },
        { title: 'Carat', metrics: 'ct' },
    ],
    data: [
        { title: 'Bit', metrics: 'B' },
        { title: 'Byte', metrics: 'Bt' },
        { title: 'Kilobyte', metrics: 'Kb' },
        { title: 'Megabyte', metrics: 'Mb' },
        { title: 'Gigabyte', metrics: 'Gb' },
        { title: 'Terabyte', metrics: 'Tb' },
        { title: 'Petabyte', metrics: 'Pb' },
    ],
};
